/*
 * Copyright (c) 2026, Pixel Brush <pixelbrush.dev>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 *
*/

use crate::enums::blocks::BLOCK_MAX;
use crate::enums::items;

pub const SLOT_EMPTY: i32 = -1; // sentinel for "no slot found"

// Get the appropriate Label for the passed id
pub fn id_to_label(id: i16) -> String {
    if id as i32 > SLOT_EMPTY {
        if (id as i32) < BLOCK_MAX.0 as i32 {
            return BLOCK_LABELS[id as usize].to_string();
        }
        if id >= items::SHOVEL_IRON.0 {
            return ITEM_LABELS[(id - items::SHOVEL_IRON.0) as usize].to_string();
        }
    }
    "Invalid".to_string()
}

pub fn w_id_to_label(id: i16) -> String {
    let label = id_to_label(id);
    let wlabel: String = label.chars().collect();
    wlabel
}

// Used to get blocks labels
pub static BLOCK_LABELS: [&str; BLOCK_MAX.0 as usize] = [
    "Air",
    "Stone",
    "Grass",
    "Dirt",
    "Cobblestone",
    "Planks",
    "Sapling",
    "Bedrock",
    "Flowing Water",
    "Still Water",
    "Flowing Lava",
    "Still Lava",
    "Sand",
    "Gravel",
    "Gold Ore",
    "Iron Ore",
    "Coal Ore",
    "Log",
    "Leaves",
    "Sponge",
    "Glass",
    "Lapis Lazuli Ore",
    "Lapis Lazuli Block",
    "Dispenser",
    "Sandstone",
    "Note Block",
    "Bed",
    "Powered Rail",
    "Detector Rail",
    "Sticky Piston",
    "Cobweb",
    "Dead Shrub",
    "Dead Bush",
    "Piston",
    "Piston Head",
    "Wool", // 35
    "36",   // 36 does not exist
    "Dandelion",
    "Rose",
    "Brown Mushroom",
    "Red Mushroom",
    "Gold Block",
    "Iron Block",
    "Double Slab",
    "Slab",
    "Bricks",
    "TNT",
    "Bookshelf",
    "Moss Stone",
    "Obsidian",
    "Torch",
    "Fire",
    "Monster Spawner",
    "Wooden Stairs",
    "Chest",
    "Redstone",
    "Diamond Ore",
    "Diamond Block",
    "Crafting Table",
    "Wheat",
    "Farmland",
    "Furnace",
    "Lit Furnace",
    "Standing Sign",
    "Wooden Door",
    "Ladder",
    "Rail",
    "Cobblestone Stairs",
    "Wall-mounted Sign",
    "Lever",
    "Stone Pressure Plate",
    "Iron Door",
    "Wooden Pressure Plate",
    "Redstone Ore",
    "Lit Redstone Ore",
    "Redstone Torch",
    "Lit Redstone Torch",
    "Stone Button",
    "Snow Layer",
    "Ice",
    "Snow Block",
    "Cactus",
    "Clay",
    "Sugar Canes",
    "Jukebox",
    "Fence",
    "Pumpkin",
    "Netherrack",
    "Soul Sand",
    "Glowstone",
    "Nether Portal",
    "Jack o' Lantern",
    "Cake",
    "Repeater (off)",
    "Repeater (on)",
    "White Stained Glass", // did not exist yet
    "Trapdoor",
];

pub static ITEM_LABELS: [&str; (items::MAX.0 - items::THRESHOLD) as usize] = [
    "Iron Shovel",
    "Iron Pickaxe",
    "Iron Axe",
    "Flint and Steel",
    "Apple",
    "Bow",
    "Arrow",
    "Coal",
    "Diamond",
    "Iron Ingot",
    "Gold Ingot",
    "Iron Sword",
    "Wooden Sword",
    "Wooden Shovel",
    "Wooden Pickaxe",
    "Wooden Axe",
    "Stone Sword",
    "Stone Shovel",
    "Stone Pickaxe",
    "Stone Axe",
    "Diamond Sword",
    "Diamond Shovel",
    "Diamond Pickaxe",
    "Diamond Axe",
    "Stick",
    "Bowl",
    "Mushroom Stew",
    "Gold Sword",
    "Gold Shovel",
    "Gold Pickaxe",
    "Gold Axe",
    "String",
    "Feather",
    "Gunpowder",
    "Wooden Hoe",
    "Stone Hoe",
    "Iron Hoe",
    "Diamond Hoe",
    "Gold Hoe",
    "Wheat Seeds",
    "Wheat",
    "Bread",
    "Leather Helmet",
    "Leather Chestplate",
    "Leather Leggings",
    "Leather Boots",
    "Chainmail Helmet",
    "Chainmail Chestplate",
    "Chainmail Leggings",
    "Chainmail Boots",
    "Iron Helmet",
    "Iron Chestplate",
    "Iron Leggings",
    "Iron Boots",
    "Diamond Helmet",
    "Diamond Chestplate",
    "Diamond Leggings",
    "Diamond Boots",
    "Golden Helmet",
    "Golden Chestplate",
    "Golden Leggings",
    "Golden Boots",
    "Flint",
    "Raw Porkchop",
    "Cooked Porkchop",
    "Painting",
    "Golden Apple",
    "Sign",
    "Wooden Door",
    "Bucket",
    "Water Bucket",
    "Lava Bucket",
    "Minecart",
    "Saddle",
    "Iron Door",
    "Redstone",
    "Snowball",
    "Boat",
    "Leather",
    "Milk Bucket",
    "Brick",
    "Clay",
    "Sugar Canes",
    "Paper",
    "Book",
    "Slimeball",
    "Minecart with Chest",
    "Minecart with Furnace",
    "Egg",
    "Compass",
    "Fishing Rod",
    "Clock",
    "Glowstone Dust",
    "Raw Fish",
    "Cooked Fish",
    "Dye",
    "Bone",
    "Sugar",
    "Cake",
    "Bed",
    "Redstone Repeater",
    "Cookie",
    "Map",
    "Shears",
    "",
];
